export const quintas = [
    {
        "id": "1",
        "name": "quinta 1",
        "street": "calle alamos",
        "address": "colonia centro",
        "num": "584",
        "estado": "Torreón",
        "lat": "25.5627",
        "lng": "-103.426",
        "costxday": "800",
        "costxweeknd": "1000",
        "costxfest": "1200",
        "id_owner": "1",
        "img": "quinta1.jpg"
    },
    {
        "id": "2",
        "name": "quinta 2",
        "street": "calle rio lerma",
        "address": "colonia estrella",
        "num": "752",
        "estado": "Torreón",
        "lat": "25.5703",
        "lng": "-103.426",
        "costxday": "650",
        "costxweeknd": "800",
        "costxfest": "1000",
        "id_owner": "1",
        "img": "quinta2.jpg"
    },
    {
        "id": "3",
        "name": "quinta 3",
        "street": "calle rio nilo",
        "address": "colonia bugambilias",
        "num": "320",
        "estado": "Torreón",
        "lat": "25.556",
        "lng": "-103.426",
        "costxday": "1100",
        "costxweeknd": "1300",
        "costxfest": "1500",
        "id_owner": "1",
        "img": "quinta3.jpg"
    },
    {
        "id": "4",
        "name": "quinta 4",
        "street": "Washington",
        "address": "Av Londres",
        "num": "580",
        "estado": "Torreón",
        "lat": "25.543",
        "lng": "-103.430",
        "costxday": "1100",
        "costxweeknd": "1300",
        "costxfest": "1500",
        "id_owner": "1",
        "img": "quinta4.jpg"
    },
    {
        "id": "5",
        "name": "quinta 5",
        "street": "Mariano Lopez Ortiz",
        "address": "Av Lerdo Tejada",
        "num": "87",
        "estado": "Torreón",
        "lat": "25.558",
        "lng": "-103.422",
        "costxday": "1100",
        "costxweeknd": "1300",
        "costxfest": "1500",
        "id_owner": "1",
        "img": "quinta3.jpg"
    }
]